import type { SafetyStaffMember, WarningEmployee, Inspector } from '../types';

export const safetyStaffMembers: SafetyStaffMember[] = [
  {
    id: 's-001',
    fullName: 'Aýgül Durdyeva',
    department: 'Ohrana Truda',
    position: 'Baş Mühendisi',
    expertise: 'Risk Assessment',
    shift: 'day',
    certificationLevel: 'expert',
    yearsOfExperience: 12,
    email: 'aygul.durdyeva@example.com',
    phone: '+993 60 123456',
  },
  {
    id: 's-002',
    fullName: 'Merdan Döwletow',
    department: 'Ohrana Truda',
    position: 'Safety Coordinator',
    expertise: 'Training & Compliance',
    shift: 'day',
    certificationLevel: 'advanced',
    yearsOfExperience: 8,
    email: 'merdan.dowletow@example.com',
    phone: '+993 65 987654',
  },
  {
    id: 's-003',
    fullName: 'Gurban Baýramow',
    department: 'Ohrana Truda',
    position: 'Field Inspector',
    expertise: 'Site Inspections',
    shift: 'night',
    certificationLevel: 'advanced',
    yearsOfExperience: 6,
    email: 'gurban.bayramow@example.com',
    phone: '+993 61 112233',
  },
  {
    id: 's-004',
    fullName: 'Aýna Hemraýewa',
    department: 'Ohrana Truda',
    position: 'Industrial Hygienist',
    expertise: 'Hazard Control',
    shift: 'day',
    certificationLevel: 'expert',
    yearsOfExperience: 9,
    email: 'ayna.hemrayewa@example.com',
    phone: '+993 62 556677',
  },
];

export const warningEmployees: WarningEmployee[] = [
  {
    id: 'w-001',
    fullName: 'Serdar Orazow',
    department: 'Production',
    position: 'Line Operator',
    warningCount: 3,
    lastWarningDate: '2025-09-12',
    activeCorrectiveAction: true,
    totalFineAmount: 120,
  },
  {
    id: 'w-002',
    fullName: 'Leýla Agamyradowa',
    department: 'Logistics',
    position: 'Forklift Driver',
    warningCount: 2,
    lastWarningDate: '2025-08-29',
    activeCorrectiveAction: false,
    totalFineAmount: 80,
  },
  {
    id: 'w-003',
    fullName: 'Rejep Allakulyýew',
    department: 'Maintenance',
    position: 'Technician',
    warningCount: 1,
    lastWarningDate: '2025-10-05',
    activeCorrectiveAction: true,
    totalFineAmount: 0,
  },
  {
    id: 'w-004',
    fullName: 'Oguljan Jumaýewa',
    department: 'Warehouse',
    position: 'Supervisor',
    warningCount: 4,
    lastWarningDate: '2025-07-21',
    activeCorrectiveAction: true,
    totalFineAmount: 240,
  },
];

export const initialInspectors: Inspector[] = [
  {
    id: 'i-001',
    fullName: 'Dowran Saparmyradow',
    department: 'Compliance Control',
    position: 'Lead Inspector',
    licenseId: 'OT-2025-001',
    region: 'Aşgabat',
    assignedSites: 5,
    lastAuditDate: '2025-09-30',
    email: 'dowran.saparmyradow@example.com',
    phone: '+993 63 445566',
  },
  {
    id: 'i-002',
    fullName: 'Selbi Nurmämmedowa',
    department: 'Compliance Control',
    position: 'Regional Inspector',
    licenseId: 'OT-2025-014',
    region: 'Balkan',
    assignedSites: 3,
    lastAuditDate: '2025-10-08',
    email: 'selbi.nurmammedowa@example.com',
    phone: '+993 64 778899',
  },
  {
    id: 'i-003',
    fullName: 'Maksat Geldiýew',
    department: 'Compliance Control',
    position: 'Inspector',
    licenseId: 'OT-2024-221',
    region: 'Mary',
    assignedSites: 4,
    lastAuditDate: '2025-09-18',
    email: 'maksat.geldiyew@example.com',
    phone: '+993 61 334455',
  },
];
