import type { Observation } from '../types';

export const mockObservations: Observation[] = [
  {
    key: '1',
    id: '0007071232',
    projectCode: 'PRJ-001',
    nameSurname: 'Ahmet Yılmaz',
    department: 'manufacturing',
    nonconformityType: 'safety',
    observationDate: '18.10.2025',
    riskLevel: 4,
    status: 'open',
    deadline: 'on_time',
    task: 'production',
    upperCategory: 'hse',
    lowerCategory: 'ppe',
  },
  {
    key: '2',
    id: '0001019876',
    projectCode: 'PRJ-002',
    nameSurname: 'Ayşe Demir',
    department: 'quality',
    nonconformityType: 'procedure',
    observationDate: '17.10.2025',
    riskLevel: 2,
    status: 'closed',
    deadline: 'delayed',
    task: 'inspection',
    upperCategory: 'quality',
    lowerCategory: 'documentation',
  },
  {
    key: '3',
    id: '0008123456',
    projectCode: 'PRJ-003',
    nameSurname: 'Mehmet Kaya',
    department: 'maintenance',
    nonconformityType: 'equipment',
    observationDate: '19.10.2025',
    riskLevel: 5,
    status: 'open',
    deadline: 'on_time',
    task: 'maintenance_repair',
    upperCategory: 'equipment',
    lowerCategory: 'machinery',
  },
];
