import type { TrainingSession } from '../types';

export const mockTrainingData: TrainingSession[] = [
  {
    id: 'TRN-001',
    title: 'Workplace Safety Induction',
    description: 'Comprehensive introduction to workplace safety policies and procedures',
    type: 'safety-induction',
    status: 'completed',
    instructor: 'John Smith',
    department: 'construction',
    location: 'Main Training Room',
    startDate: '2024-10-01',
    endDate: '2024-10-01',
    duration: 4,
    capacity: 30,
    enrolled: 28,
    attendees: [],
    materials: ['Safety Manual.pdf', 'PPE Guidelines.pdf', 'Emergency Procedures.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 96.4,
  },
  {
    id: 'TRN-002',
    title: 'Forklift Operation Certification',
    description: 'Hands-on training for safe forklift operation and certification',
    type: 'equipment-training',
    status: 'in-progress',
    instructor: 'Sarah Johnson',
    department: 'warehouse',
    location: 'Warehouse Zone A',
    startDate: '2024-10-15',
    endDate: '2024-10-17',
    duration: 12,
    capacity: 15,
    enrolled: 15,
    attendees: [],
    materials: ['Forklift Manual.pdf', 'Safety Checklist.pdf'],
    certificate: true,
    mandatory: false,
    completionRate: 60.0,
  },
  {
    id: 'TRN-003',
    title: 'Fire Safety & Emergency Response',
    description: 'Fire prevention, evacuation procedures, and emergency response training',
    type: 'emergency-response',
    status: 'scheduled',
    instructor: 'Michael Chen',
    department: 'manufacturing',
    location: 'Assembly Hall',
    startDate: '2024-10-25',
    endDate: '2024-10-25',
    duration: 3,
    capacity: 50,
    enrolled: 42,
    attendees: [],
    materials: ['Fire Safety Guide.pdf', 'Evacuation Map.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 0,
  },
  {
    id: 'TRN-004',
    title: 'OSHA Compliance Training',
    description: 'Understanding and implementing OSHA safety standards',
    type: 'compliance-training',
    status: 'completed',
    instructor: 'Emily Rodriguez',
    department: 'engineering',
    location: 'Conference Room B',
    startDate: '2024-09-20',
    endDate: '2024-09-21',
    duration: 8,
    capacity: 25,
    enrolled: 23,
    attendees: [],
    materials: ['OSHA Standards.pdf', 'Compliance Checklist.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 91.3,
  },
  {
    id: 'TRN-005',
    title: 'Confined Space Entry Training',
    description: 'Safe practices for working in confined spaces',
    type: 'safety-induction',
    status: 'completed',
    instructor: 'David Lee',
    department: 'maintenance',
    location: 'Field Training Area',
    startDate: '2024-09-10',
    endDate: '2024-09-11',
    duration: 6,
    capacity: 20,
    enrolled: 18,
    attendees: [],
    materials: ['Confined Space Manual.pdf', 'Gas Detection Guide.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 90.0,
  },
  {
    id: 'TRN-006',
    title: 'First Aid & CPR Certification',
    description: 'Basic first aid and CPR training with certification',
    type: 'emergency-response',
    status: 'scheduled',
    instructor: 'Lisa Anderson',
    department: 'logistics',
    location: 'Training Center',
    startDate: '2024-11-05',
    endDate: '2024-11-06',
    duration: 8,
    capacity: 25,
    enrolled: 20,
    attendees: [],
    materials: ['First Aid Manual.pdf', 'CPR Guide.pdf'],
    certificate: true,
    mandatory: false,
    completionRate: 0,
  },
  {
    id: 'TRN-007',
    title: 'Hazardous Materials Handling',
    description: 'Safe handling, storage, and disposal of hazardous materials',
    type: 'compliance-training',
    status: 'in-progress',
    instructor: 'Robert Williams',
    department: 'manufacturing',
    location: 'Safety Training Lab',
    startDate: '2024-10-18',
    endDate: '2024-10-19',
    duration: 10,
    capacity: 20,
    enrolled: 18,
    attendees: [],
    materials: ['HAZMAT Guidelines.pdf', 'SDS Sheets.pdf', 'Spill Response.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 50.0,
  },
  {
    id: 'TRN-008',
    title: 'Electrical Safety Awareness',
    description: 'Understanding electrical hazards and safety practices',
    type: 'safety-induction',
    status: 'completed',
    instructor: 'Jennifer Martinez',
    department: 'engineering',
    location: 'Electrical Workshop',
    startDate: '2024-09-15',
    endDate: '2024-09-15',
    duration: 4,
    capacity: 30,
    enrolled: 27,
    attendees: [],
    materials: ['Electrical Safety Manual.pdf', 'Lockout-Tagout Guide.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 90.0,
  },
  {
    id: 'TRN-009',
    title: 'Leadership in Safety Culture',
    description: 'Developing leadership skills to promote safety culture',
    type: 'skill-development',
    status: 'scheduled',
    instructor: 'Thomas Brown',
    location: 'Executive Training Room',
    startDate: '2024-11-10',
    endDate: '2024-11-12',
    duration: 16,
    capacity: 20,
    enrolled: 15,
    attendees: [],
    materials: ['Leadership Guide.pdf', 'Safety Culture.pdf'],
    certificate: true,
    mandatory: false,
    completionRate: 0,
  },
  {
    id: 'TRN-010',
    title: 'Fall Protection Refresher',
    description: 'Annual refresher course on fall protection equipment and procedures',
    type: 'refresher-course',
    status: 'scheduled',
    instructor: 'Amanda Davis',
    department: 'construction',
    location: 'Outdoor Training Area',
    startDate: '2024-10-30',
    endDate: '2024-10-30',
    duration: 4,
    capacity: 35,
    enrolled: 32,
    attendees: [],
    materials: ['Fall Protection Guide.pdf', 'Equipment Inspection.pdf'],
    certificate: true,
    mandatory: true,
    completionRate: 0,
  },
];
