/**
 * Mock Employee Data
 *
 * Comprehensive employee database for tenant admin panel
 */

export interface Employee {
  [key: string]: unknown;
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  position: string;
  department: string;
  hireDate: string;
  status: 'active' | 'on_leave' | 'suspended' | 'terminated';
  avatar?: string;

  // Safety-specific fields
  safetyRole?: 'worker' | 'safety_team' | 'inspector' | 'head_of_safety';
  lastTrainingDate?: string;
  trainingExpiryDate?: string;
  certifications: string[];
  incidentCount: number;
  observationsSubmitted: number;

  // Contact & Emergency
  emergencyContact?: {
    name: string;
    relationship: string;
    phone: string;
  };

  // Location
  workLocation: string;
  shift?: 'day' | 'night' | 'rotating';

  createdAt: string;
  updatedAt: string;
}

export const MOCK_EMPLOYEES: Employee[] = [
  // Management & Safety Team
  {
    id: 'emp_001',
    employeeNumber: 'EMP-001',
    firstName: 'John',
    lastName: 'Smith',
    email: 'john.smith@acme.com',
    phone: '+1-555-0101',
    position: 'Head of Safety',
    department: 'Safety & Compliance',
    hireDate: '2020-01-15',
    status: 'active',
    safetyRole: 'head_of_safety',
    lastTrainingDate: '2025-09-15',
    trainingExpiryDate: '2026-09-15',
    certifications: ['OSHA 30-Hour', 'First Aid', 'CPR', 'Safety Manager Certification'],
    incidentCount: 0,
    observationsSubmitted: 45,
    emergencyContact: {
      name: 'Jane Smith',
      relationship: 'Spouse',
      phone: '+1-555-0102',
    },
    workLocation: 'Main Office',
    shift: 'day',
    createdAt: '2020-01-15T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_002',
    employeeNumber: 'EMP-002',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@acme.com',
    phone: '+1-555-0103',
    position: 'Safety Inspector',
    department: 'Safety & Compliance',
    hireDate: '2021-03-20',
    status: 'active',
    safetyRole: 'inspector',
    lastTrainingDate: '2025-08-20',
    trainingExpiryDate: '2026-08-20',
    certifications: ['OSHA 30-Hour', 'Certified Safety Inspector', 'Fall Protection'],
    incidentCount: 0,
    observationsSubmitted: 78,
    emergencyContact: {
      name: 'Mike Johnson',
      relationship: 'Spouse',
      phone: '+1-555-0104',
    },
    workLocation: 'Main Office',
    shift: 'day',
    createdAt: '2021-03-20T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_003',
    employeeNumber: 'EMP-003',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@acme.com',
    phone: '+1-555-0105',
    position: 'Safety Officer',
    department: 'Safety & Compliance',
    hireDate: '2021-06-10',
    status: 'active',
    safetyRole: 'safety_team',
    lastTrainingDate: '2025-07-10',
    trainingExpiryDate: '2026-07-10',
    certifications: ['OSHA 10-Hour', 'First Aid', 'Fire Safety'],
    incidentCount: 0,
    observationsSubmitted: 52,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2021-06-10T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_004',
    employeeNumber: 'EMP-004',
    firstName: 'Emily',
    lastName: 'Davis',
    email: 'emily.davis@acme.com',
    phone: '+1-555-0106',
    position: 'Safety Inspector',
    department: 'Safety & Compliance',
    hireDate: '2022-01-05',
    status: 'active',
    safetyRole: 'inspector',
    lastTrainingDate: '2025-09-01',
    trainingExpiryDate: '2026-09-01',
    certifications: ['OSHA 30-Hour', 'Confined Space', 'Hazmat Awareness'],
    incidentCount: 0,
    observationsSubmitted: 63,
    workLocation: 'Site B',
    shift: 'rotating',
    createdAt: '2022-01-05T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },

  // Construction Workers
  {
    id: 'emp_005',
    employeeNumber: 'EMP-005',
    firstName: 'David',
    lastName: 'Rodriguez',
    email: 'david.rodriguez@acme.com',
    phone: '+1-555-0107',
    position: 'Construction Foreman',
    department: 'Construction',
    hireDate: '2019-05-12',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-06-12',
    trainingExpiryDate: '2026-06-12',
    certifications: ['OSHA 10-Hour', 'Scaffold Safety', 'Heavy Equipment'],
    incidentCount: 1,
    observationsSubmitted: 23,
    emergencyContact: {
      name: 'Maria Rodriguez',
      relationship: 'Spouse',
      phone: '+1-555-0108',
    },
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2019-05-12T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_006',
    employeeNumber: 'EMP-006',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@acme.com',
    phone: '+1-555-0109',
    position: 'Carpenter',
    department: 'Construction',
    hireDate: '2020-08-25',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-05-20',
    trainingExpiryDate: '2026-05-20',
    certifications: ['OSHA 10-Hour', 'Fall Protection'],
    incidentCount: 0,
    observationsSubmitted: 12,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2020-08-25T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_007',
    employeeNumber: 'EMP-007',
    firstName: 'Robert',
    lastName: 'Martinez',
    email: 'robert.martinez@acme.com',
    phone: '+1-555-0110',
    position: 'Electrician',
    department: 'Electrical',
    hireDate: '2021-02-14',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-08-10',
    trainingExpiryDate: '2026-08-10',
    certifications: ['OSHA 10-Hour', 'Electrical Safety', 'Arc Flash'],
    incidentCount: 0,
    observationsSubmitted: 18,
    workLocation: 'Site B',
    shift: 'day',
    createdAt: '2021-02-14T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_008',
    employeeNumber: 'EMP-008',
    firstName: 'Linda',
    lastName: 'Anderson',
    email: 'linda.anderson@acme.com',
    phone: '+1-555-0111',
    position: 'Plumber',
    department: 'Plumbing',
    hireDate: '2020-11-30',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-07-15',
    trainingExpiryDate: '2026-07-15',
    certifications: ['OSHA 10-Hour', 'Confined Space'],
    incidentCount: 1,
    observationsSubmitted: 9,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2020-11-30T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_009',
    employeeNumber: 'EMP-009',
    firstName: 'William',
    lastName: 'Taylor',
    email: 'william.taylor@acme.com',
    phone: '+1-555-0112',
    position: 'Heavy Equipment Operator',
    department: 'Operations',
    hireDate: '2019-09-18',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-09-18',
    trainingExpiryDate: '2026-09-18',
    certifications: ['OSHA 10-Hour', 'Heavy Equipment Certification', 'Signal Person'],
    incidentCount: 0,
    observationsSubmitted: 15,
    workLocation: 'Site B',
    shift: 'day',
    createdAt: '2019-09-18T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_010',
    employeeNumber: 'EMP-010',
    firstName: 'Jessica',
    lastName: 'Thomas',
    email: 'jessica.thomas@acme.com',
    phone: '+1-555-0113',
    position: 'Welder',
    department: 'Fabrication',
    hireDate: '2021-07-22',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-06-01',
    trainingExpiryDate: '2026-06-01',
    certifications: ['OSHA 10-Hour', 'Welding Safety', 'Hot Work Permit'],
    incidentCount: 0,
    observationsSubmitted: 14,
    workLocation: 'Site A',
    shift: 'night',
    createdAt: '2021-07-22T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },

  // Additional Workers
  {
    id: 'emp_011',
    employeeNumber: 'EMP-011',
    firstName: 'Christopher',
    lastName: 'Garcia',
    email: 'chris.garcia@acme.com',
    phone: '+1-555-0114',
    position: 'Laborer',
    department: 'Construction',
    hireDate: '2022-04-10',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-04-10',
    trainingExpiryDate: '2026-04-10',
    certifications: ['OSHA 10-Hour'],
    incidentCount: 0,
    observationsSubmitted: 5,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2022-04-10T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_012',
    employeeNumber: 'EMP-012',
    firstName: 'Amanda',
    lastName: 'Lee',
    email: 'amanda.lee@acme.com',
    phone: '+1-555-0115',
    position: 'Painter',
    department: 'Finishing',
    hireDate: '2022-06-15',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-05-15',
    certifications: ['OSHA 10-Hour', 'Respiratory Protection'],
    incidentCount: 0,
    observationsSubmitted: 8,
    workLocation: 'Site B',
    shift: 'day',
    createdAt: '2022-06-15T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_013',
    employeeNumber: 'EMP-013',
    firstName: 'Daniel',
    lastName: 'White',
    email: 'daniel.white@acme.com',
    phone: '+1-555-0116',
    position: 'Site Supervisor',
    department: 'Operations',
    hireDate: '2020-03-08',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-08-01',
    trainingExpiryDate: '2026-08-01',
    certifications: ['OSHA 30-Hour', 'First Aid', 'Site Management'],
    incidentCount: 0,
    observationsSubmitted: 31,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2020-03-08T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_014',
    employeeNumber: 'EMP-014',
    firstName: 'Michelle',
    lastName: 'Harris',
    email: 'michelle.harris@acme.com',
    phone: '+1-555-0117',
    position: 'Quality Inspector',
    department: 'Quality Control',
    hireDate: '2021-09-12',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-07-20',
    trainingExpiryDate: '2026-07-20',
    certifications: ['OSHA 10-Hour', 'Quality Management'],
    incidentCount: 0,
    observationsSubmitted: 22,
    workLocation: 'Site B',
    shift: 'day',
    createdAt: '2021-09-12T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_015',
    employeeNumber: 'EMP-015',
    firstName: 'Kevin',
    lastName: 'Clark',
    email: 'kevin.clark@acme.com',
    phone: '+1-555-0118',
    position: 'HVAC Technician',
    department: 'HVAC',
    hireDate: '2022-01-20',
    status: 'on_leave',
    safetyRole: 'worker',
    lastTrainingDate: '2025-01-20',
    trainingExpiryDate: '2026-01-20',
    certifications: ['OSHA 10-Hour', 'HVAC Safety', 'Refrigerant Handling'],
    incidentCount: 0,
    observationsSubmitted: 11,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2022-01-20T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_016',
    employeeNumber: 'EMP-016',
    firstName: 'Patricia',
    lastName: 'Lewis',
    email: 'patricia.lewis@acme.com',
    phone: '+1-555-0119',
    position: 'Mason',
    department: 'Construction',
    hireDate: '2020-07-05',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-06-05',
    trainingExpiryDate: '2026-06-05',
    certifications: ['OSHA 10-Hour', 'Scaffold Safety'],
    incidentCount: 2,
    observationsSubmitted: 7,
    workLocation: 'Site B',
    shift: 'day',
    createdAt: '2020-07-05T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_017',
    employeeNumber: 'EMP-017',
    firstName: 'Steven',
    lastName: 'Walker',
    email: 'steven.walker@acme.com',
    phone: '+1-555-0120',
    position: 'Roofer',
    department: 'Roofing',
    hireDate: '2021-11-08',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-08-08',
    trainingExpiryDate: '2026-08-08',
    certifications: ['OSHA 10-Hour', 'Fall Protection', 'Roof Safety'],
    incidentCount: 1,
    observationsSubmitted: 6,
    workLocation: 'Site A',
    shift: 'day',
    createdAt: '2021-11-08T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_018',
    employeeNumber: 'EMP-018',
    firstName: 'Nancy',
    lastName: 'Hall',
    email: 'nancy.hall@acme.com',
    phone: '+1-555-0121',
    position: 'Project Manager',
    department: 'Management',
    hireDate: '2019-02-28',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-09-28',
    trainingExpiryDate: '2026-09-28',
    certifications: ['OSHA 30-Hour', 'PMP', 'Project Safety'],
    incidentCount: 0,
    observationsSubmitted: 28,
    workLocation: 'Main Office',
    shift: 'day',
    createdAt: '2019-02-28T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_019',
    employeeNumber: 'EMP-019',
    firstName: 'Brian',
    lastName: 'Allen',
    email: 'brian.allen@acme.com',
    phone: '+1-555-0122',
    position: 'Equipment Mechanic',
    department: 'Maintenance',
    hireDate: '2020-10-14',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-07-14',
    trainingExpiryDate: '2026-07-14',
    certifications: ['OSHA 10-Hour', 'Lockout/Tagout', 'Diesel Mechanic'],
    incidentCount: 0,
    observationsSubmitted: 10,
    workLocation: 'Site B',
    shift: 'rotating',
    createdAt: '2020-10-14T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
  {
    id: 'emp_020',
    employeeNumber: 'EMP-020',
    firstName: 'Donna',
    lastName: 'Young',
    email: 'donna.young@acme.com',
    phone: '+1-555-0123',
    position: 'Administrative Assistant',
    department: 'Administration',
    hireDate: '2021-04-03',
    status: 'active',
    safetyRole: 'worker',
    lastTrainingDate: '2025-04-03',
    certifications: ['Office Safety', 'First Aid'],
    incidentCount: 0,
    observationsSubmitted: 3,
    workLocation: 'Main Office',
    shift: 'day',
    createdAt: '2021-04-03T00:00:00Z',
    updatedAt: '2025-10-15T00:00:00Z',
  },
];

// Helper functions
export function getEmployeeById(id: string): Employee | undefined {
  return MOCK_EMPLOYEES.find((emp) => emp.id === id);
}

export function getEmployeesByDepartment(department: string): Employee[] {
  return MOCK_EMPLOYEES.filter((emp) => emp.department === department);
}

export function getEmployeesBySafetyRole(role: Employee['safetyRole']): Employee[] {
  return MOCK_EMPLOYEES.filter((emp) => emp.safetyRole === role);
}

export function getActiveEmployees(): Employee[] {
  return MOCK_EMPLOYEES.filter((emp) => emp.status === 'active');
}

export function getEmployeesWithExpiredTraining(): Employee[] {
  const now = new Date();
  return MOCK_EMPLOYEES.filter((emp) => {
    if (!emp.trainingExpiryDate) return false;
    return new Date(emp.trainingExpiryDate) < now;
  });
}

export function getEmployeesWithUpcomingTrainingExpiry(days: number = 30): Employee[] {
  const now = new Date();
  const futureDate = new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

  return MOCK_EMPLOYEES.filter((emp) => {
    if (!emp.trainingExpiryDate) return false;
    const expiryDate = new Date(emp.trainingExpiryDate);
    return expiryDate >= now && expiryDate <= futureDate;
  });
}

export const DEPARTMENTS = [
  'Safety & Compliance',
  'Construction',
  'Electrical',
  'Plumbing',
  'Operations',
  'Fabrication',
  'Finishing',
  'Quality Control',
  'HVAC',
  'Roofing',
  'Management',
  'Maintenance',
  'Administration',
];

export const POSITIONS = [
  'Head of Safety',
  'Safety Inspector',
  'Safety Officer',
  'Construction Foreman',
  'Carpenter',
  'Electrician',
  'Plumber',
  'Heavy Equipment Operator',
  'Welder',
  'Laborer',
  'Painter',
  'Site Supervisor',
  'Quality Inspector',
  'HVAC Technician',
  'Mason',
  'Roofer',
  'Project Manager',
  'Equipment Mechanic',
  'Administrative Assistant',
];

export const WORK_LOCATIONS = ['Main Office', 'Site A', 'Site B', 'Site C'];

export const CERTIFICATIONS = [
  'OSHA 10-Hour',
  'OSHA 30-Hour',
  'First Aid',
  'CPR',
  'Fall Protection',
  'Scaffold Safety',
  'Confined Space',
  'Electrical Safety',
  'Arc Flash',
  'Heavy Equipment Certification',
  'Welding Safety',
  'Hot Work Permit',
  'Respiratory Protection',
  'Site Management',
  'Quality Management',
  'HVAC Safety',
  'Refrigerant Handling',
  'Roof Safety',
  'PMP',
  'Project Safety',
  'Lockout/Tagout',
  'Diesel Mechanic',
  'Office Safety',
  'Safety Manager Certification',
  'Certified Safety Inspector',
  'Hazmat Awareness',
  'Signal Person',
];
