import type { Department } from '../types';

export const mockDepartments: Department[] = [
  {
    key: '1',
    department: 'İmalat',
    nonconformityType: 'Güvenlik',
    observationDate: '18.10.2025',
    riskLevel: 4,
    status: 'AÇIK',
    deadline: 'ZAMANINDA',
    task: 'Üretim',
    upperCategory: 'İSG',
    lowerCategory: 'KKD',
  },
  {
    key: '2',
    department: 'Kalite',
    nonconformityType: 'Prosedür',
    observationDate: '17.10.2025',
    riskLevel: 2,
    status: 'KAPALI',
    deadline: 'GECIKMELI',
    task: 'Kontrol',
    upperCategory: 'Kalite',
    lowerCategory: 'Dokümantasyon',
  },
  {
    key: '3',
    department: 'Bakım',
    nonconformityType: 'Ekipman',
    observationDate: '19.10.2025',
    riskLevel: 5,
    status: 'AÇIK',
    deadline: 'ZAMANINDA',
    task: 'Bakım Onarım',
    upperCategory: 'Ekipman',
    lowerCategory: 'Makine',
  },
  {
    key: '4',
    department: 'Yönetim',
    nonconformityType: 'Dokümantasyon',
    observationDate: '16.10.2025',
    riskLevel: 1,
    status: 'KAPALI',
    deadline: 'ZAMANINDA',
    task: 'İdari İşler',
    upperCategory: 'Yönetim',
    lowerCategory: 'Evrak',
  },
];
